api:
  id: "20548368"
  
http:
  host: "0.0.0.0"
  port: "8085"
  timeout: "30000"
  
salesforce:
  url: "https://login.salesforce.com" 
  timeout: "30000"
  username: "${salesforce.username}"
  password: "${salesforce.password}"
  securityToken: ""
  externalIdField: "External_Id__c"